Read IGRF coefficients from file
aburrell/apexpy pull request #24
Opened 2020-05-11 11:44 UTC by sputnik-a

IGRF coefficients are directly read from ASCII-file instead of using
hard-coded values. This omits adding the coefficients manually in
the future.

2020-05-12 19:59 UTC, asreimer commented
Hi @sputnik-a,

Can you please redo this PR? Start from the develop branch (as per [contributing guidelines](https://github.com/aburrell/apexpy/blob/master/CONTRIBUTING.rst)? You should be able to simply cherrypick the commits you made here.

Thanks!

2021-02-05 18:30 UTC, aburrell requested changes
I rebased the pull request and resolved the conflicts.  I verified the coefficient file, but am having trouble getting the fortran code to work (and thereby having trouble getting the python to install).  I am going to try and rope Emmert in on this, but do feel free to help with the troubleshooting.

2021-02-05 18:30 UTC, aburrell commented on AUTHORS.rst
> +* Gregory Starr
Please add your name to the end of the Author list.

2021-02-09 13:27 UTC, aburrell approved these changes
This looks great, thank you!

2021-02-09 13:28 UTC, merged

2021-02-12 08:25 UTC, sputnik-a commented
> This looks great, thank you!

Thanks! I am glad everything is working now. Sorry I was busy the last weeks - let me know when I can do anything else with the Fortran part in the future or in case of problems with the IGRF part.